sudo: required
dist: trusty
language: generic
compiler:
  - gcc
cache:
  directories:
    - $HOME/.ccache  # can be any valid cache location
env:
  global:
    - LIBGL_ALWAYS_SOFTWARE=1
    - VERBOSE_OUTPUT='false'
    - CATKIN_CONFIG='--no-install'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
    - CCACHE_DIR=$HOME/.ccache
matrix:
  include:
    - env: USE_DEB=true ROS_DISTRO=indigo PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true ROSDEP_SKIP_KEYS="gazebo gazebo_msgs gazebo_plugins gazebo_ros gazebo_ros_control gazebo_ros_pkgs"
    - env: USE_DEB=true ROS_DISTRO=kinetic PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true
    - env: USE_DEB=true ROS_DISTRO=kinetic PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true ROSDEP_SKIP_KEYS="gazebo gazebo_msgs gazebo_plugins gazebo_ros gazebo_ros_control gazebo_ros_pkgs"
    - env: USE_DEB=true ROS_DISTRO=lunar PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true
    - env: USE_DEB=true ROS_DISTRO=melodic PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true
  allow_failures:
    - env: USE_DEB=true ROS_DISTRO=indigo PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true ROSDEP_SKIP_KEYS="gazebo gazebo_msgs gazebo_plugins gazebo_ros gazebo_ros_control gazebo_ros_pkgs"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8c9c6426a721fbb8341
    on_success: change
    on_failure: always
    on_start: never
